name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1
flutter:
  assets:
    - assets/images/black.jpg
    - assets/images/download.jpeg
environment:
  sdk: ^3.1.1
dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  agora_rtc_engine: ^6.2.6
  permission_handler: 
  http: ^1.1.2
    

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
 


